### ISSUE TITLE
visualization 

### ISSUE THREAD

**Issue by fabian-s** [fabian-s/tidyfun#10]
- [x] for `base` graphics: `matlines` with reasonable defaults, prolly.
- [ ] make a decent, customizable, correct version of a functional boxplot (needs #7) 
- [ ] possibly, for `ggplot`: little "inset" (sparkline-like) symbols via `geom_function` to visualize  e.g. function shapes over spatial locations. could also use little colourbars like a spread-out lasagna plot. 
(rather tricky, probably: does `ggplot2` even accept data with list-columns / list-columns as args to `aes`?) 

Example: 
![image](https://user-images.githubusercontent.com/998541/35946732-3f115ff4-0c65-11e8-8247-12d5628e4f72.png)
 
- [ ] `add`-argument for funplot to add to an existing ggplot?
- [x] `geom_spaghetti`
- [x] `geom_lasagna`
- [ ] `funplot ` defaults for irregular to be discussed  (@jeff-goldsmith )

**Comment by fabian-s** [comment]
jeff says:
write `geom_spaghetti`, `geom_lasagna`

**Comment by fabian-s** [comment]
see https://cran.r-project.org/web/packages/ggplot2/vignettes/extending-ggplot2.html

**Comment by adibender** [comment]
examples for custom `geom`s (for nested data structures): https://github.com/mjskay/tidybayes/

**Comment by fabian-s** [comment]
52e27f0 is still a hack for lasagna: facetting is broken (see #36)

**Comment by fabian-s** [comment]
Closing this to break it out in separate issues:

- clean up Geom / Stat implementations #39
- functional boxplots #40
- better defaults for funplot #41
- `geom_tfglyph` for insets #42
