### ISSUE TITLE
find better names

### ISSUE THREAD

**Issue by fabian-s** [fabian-s/tidyfun#16]
`fvector` , `feval`, etc. are terrible.

**Comment by fabian-s** [comment]
we actually like `fvector`.
let's just do `tidy_XX` and steal the names we like

**Comment by fabian-s** [comment]
.. same thing for `argvals` and `id`

**Comment by jeff-goldsmith** [comment]
i'm starting to lean towards `tf_` as a prefix over `tidy` (and, elsewhere, using `rf_` for `refund` functions ...)

not trying to reopen old wounds, but is there a clear winner between `tidy_fd` (which is, i know, inconsistent with function names) and `fvector`? or maybe `tidy_fobs` for `feval` and `tidy_fvec` for `fvector`? 

i like `id`. maybe `arg` and `value` for the input and output of the function? i don't know why `argvals` would be plural but `value` would be singular ...

**Comment by fabian-s** [comment]
**class names:**

We need names for the abstract superclass of (vectors of ) functional data and names that derive from it 

- for functional data that are represented internally as tuples (x, f(x)) 
- for functional data that are represented internally as linear combinations of a set of basis functions (splines, FPCs, wavelets, whatever)

How about `tf` for the abstract super class, `tfd` [**t**idy **f**unctional **d**ata] for `feval` and `tfb` for `fbase`?

(I like this because it's short and it plays off the `sf`-standard -- "simple features" -- that is used for geo-referenced data, https://github.com/r-spatial/sf)

--------------------

Agreed on the second point. Let's do (`id`, `arg`, `value`).

**Comment by jeff-goldsmith** [comment]
Sounds good. I guess `tfb` stands for **t**idy **f**unctional **b**asis ...?
