### ISSUE TITLE
functionality for  zooming in / truncating functions

### ISSUE THREAD

**Issue by fabian-s** [fabian-s/tidyfun#23]
see #21. 
Not easy to do "give me these functions on [0, 0.5] instead of [0,1]" currently.

**Comment by jeff-goldsmith** [comment]
mentioned in an email somewhere -- i wonder if this can be combined with the `evaluate` function, so that `evaluate(funs, argvals = 1:10)` evaluates on a grid and `evaluate(funs, argvals < 10)` zooms.
