### ISSUE TITLE
Grouped dplyr-operations do not work

### ISSUE THREAD

**Issue by fabian-s** [fabian-s/tidyfun#25]
```
test_df <-  with(DTI, data.frame(id = ID, sex = sex)); test_df$cca <- feval(DTI$cca)
test_df %>% group_by(sex) %>% summarize(mean_cca = mean(cca), sd_cca = sd(cca))
#Error in summarise_impl(.data, dots) : 
#  Evaluation error: Assertion on 'length(argvals) %in% c(1, length(x))'
```

problem: dplyr does not create subsets by subsetting with [], it does weird C++ shit and then copies attributes (so length of argvals is not the length of subsetted  irregular `feval`...)

Try with `fbase` where this should not be an issue:
```
test_df %>% mutate(cca = fbase(cca)) %>% group_by(sex) %>% summarize(m = mean(cca))
#Error in summarise_impl(.data, dots) : 
# Evaluation error: Argument 1 must have names.
```
Hard to debug because dplyr is almost undebuggable since it keeps calling C++ and then calling R from C++ again (I think), but it looks like the `fvector` gets evaluated to an (unnamed?!?) list of tibbles for some reason somewhere and the error above is then thrown by `bind_rows_` -- not sure where/why `bind_rows_` is used here.

Related as well: `nth` does not work either (not even for ungrouped df) since it uses `[[` and accessing fvectors via `[[` loses all attributes. This should probably simply subset the vector.

**Comment by fabian-s** [comment]
List of similar issues for other non-standard data types: https://github.com/tidyverse/dplyr/issues/2432.

@jeff-goldsmith : this seems rather hopeless, since not a lot has happened to resolve these earlier issues for at least one year. Tibblyverse people keep mentioning a new [`vctrs`](https://github.com/krlmlr/vctrs/tree/f-classes-draft) package supposed to resolve these issues by defining an abstract superclass for vector-like objects, IIUC, but development on that seems to be stalled.

Not sure at all how to proceed/work around this. 

If grouped mutate/summarize etc don't work we won't succeed in writing a `tidyverse`-style UI for functional data, obviously. 

I don't understand the code in https://github.com/tidyverse/dplyr/blob/4d6fe4cc61367b8fa0aa181b520f0a6e86cc856f/src/summarise.cpp#L36 at all, so I don''t know what to change how to make `fvector` more compatible with `dplyr`. 
Any ideas?

**Comment by jeff-goldsmith** [comment]
well. shit.

this definitely limits the scope of what we can do, and it limits it ways that really matter -- the example you have above, of grouping by sex and taking the within-group mean of a functional variable, is definitely the kind of thing that will come up. 

the only thing i can think to do, basically, is to ignore the stuff we can't do until the tibblefolk have this sorted out (which might never happen), and to focus on the stuff we can do -- using `fvector`s as a way to organize functional datasets, manipulation of individual observations using `mutate` + `map` (e.g. to smooth individual curves), and focusing of the development of downstream tools for analysis.
