### ISSUE TITLE
Simple smoothing methods for fevals

### ISSUE THREAD

**Issue by fabian-s** [fabian-s/tidyfun#32]
- [ ] running means 
- [ ] running medians 
- [ ] savitzky-golay
etc.

**Comment by jeff-goldsmith** [comment]
suggestion: call this `tf_smooth` with options for different methods, and have it work for fvectors:

```
fun_df %>%
  mutate(smooth_funs = tf_smooth(funs))
```

i'm thinking of this as a replacement for something like the following, but correct me if this isn't what you intend.

```
fun_df %>%
  mutate(smooth_funs = 
    map(funs, ~ tibble(.x) %>% gam(value ~ s(argval), data = data) %>% predict() )
```

**Comment by fabian-s** [comment]
@jeff-goldsmith  i was not thinking about spline smoothing here, but more simple local methods.  

The lines above I would do as:
```
fun_df %>%
  mutate(smooth_funs =  tfb(funs))
```
or, if I really really don't want a basis representation 
```
fun_df %>%
  mutate(smooth_funs =  tfd(tfb(funs)))
```
