### ISSUE TITLE
tf_nest

### ISSUE THREAD

**Issue by fabian-s** [fabian-s/tidyfun#33]
This is too clunky: 

```r
mouse_df %>% 
    select(id, time, genotype, cohort, sys_mm_hg) %>% 
    feval(id = "id", argvals = "time", value = "sys_mm_hg")
```

We want something like:

```r
str(mouse_df)
#Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	190080 obs. of  9 variables:
# $ id        : num  1 1 1 1 1 1 1 1 1 1 ...
# $ time      : num  1 2 3 4 5 6 7 8 9 10 ...
# $ genotype  : Factor w/ 3 levels "genotype_1","genotype_2",..: 1 1 1 1 1 1 1 1 1 1 ...
# $ cohort    : Factor w/ 3 levels "cohort_1","cohort_2",..: 1 1 1 1 1 1 1 1 1 1 ...
# $ light_dark: num  1 1 1 1 1 1 1 1 1 1 ...
# $ sys_mm_hg : num  146 145 144 151 150 ...
# $ dia_mm_hg : num  114 113 113 117 116 ...
# $ map_mm_hg : num  131 130 129 135 133 ...
# $ hr_bpm    : num  748 732 745 752 723 ...
mouse_df %>% tf_nest(id, time, light_dark:hr_bpm)
```

to create a data.frame with all these functional covariates as fevals 

Needs:
- quasiquotation
- use tidyselect::vars_select for args

**Comment by jeff-goldsmith** [comment]
one difference with `tidyr::nest()` is that we're presumably only going to nest the `value` columns (e.g. `light_dark:hr_bpm`) using `time` as the argvals and `id` as the id -- if there are any other (curve-level) covariates they'll be kept.

**Comment by fabian-s** [comment]
This is done. I'm a god amongst men, a beast of beauty, a shining star.

**Comment by jeff-goldsmith** [comment]
truly, you are a beacon for all ...
