### ISSUE TITLE
tf_gather

### ISSUE THREAD

**Issue by fabian-s** [fabian-s/tidyfun#34]
see #33 . do stuff the tidyverse way!

e.g. `tf_gather(rcst1:rcst55)` - this will **shorten** the data.frame, though? so need to make sure no other covariate info gets lost...

**Comment by jeff-goldsmith** [comment]
i don't think this will shorten the data.frame -- should result in the same number of rows, with `rcst1:rcst55` replaced with fevals, right?

in any case, i'm not sure what to do with the column names. if there's a clear prefix (like there is here), it would be super for the feval to be called that prefix (e.g. `rcst` or `cca`, depending on what gets gathered). i think `janitor::clean_names` has a way for detecting prefixes, which might be useful. 

if argvals aren't built into column names, i suppose we'll use the default assumption (equally spaced grid, common across subjects).
