### ISSUE TITLE
pkgdown custom reference page not rendered 

### ISSUE THREAD

**Issue by fabian-s** [fabian-s/tidyfun#59]
Things I tried:
- adding `_pkgdown.yml`  to top level directory in `master` and running `pkgdown::build_site` does not trigger any building of a proper page (only README visible) 
- pushing the docs subdirector into a separate gh-pages folder and copying the  `_pkgdown.yml` there used to work, but doesn't any more -- the reference page does not get rendered, instead we get the standard list of all functions

**Comment by jeff-goldsmith** [comment]
similar issue with article ordering -- adding in desired order to `_pkgdown.yml` doesn't seem to list to do anything, and articles appear alphabetically. it seems this was [reported and fixed](https://github.com/r-lib/pkgdown/commit/d4e9509f99265a551f03ef2696d2f0393f24103c) but i'm getting nowhere ...

**Comment by fabian-s** [comment]
i fixed it -- also no more need to keep an extra gh-pages branch, the site is built directly from the /docs folder in master now.
